spring:
  profiles:
    default: local
    active: local
    
---

spring:
  profiles: local
  
  datasource:
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl: true
  h2:
    console:
      enabled: true

server:
  port: 8081  
  
jdbc:
  user: db2admin
  pass: db2admin
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
  
  
hibernate:
  dialect: org.hibernate.dialect.H2Dialect      